### PR TITLE
Implement new api for write without response

### PR DESCRIPTION
**Pull request by Preejar**
Adding new api named WriteCommand to write value of
 attribute. No error response or write response sent
 in response to this command.Added opcode for this as 0x52.
 Also introduced new execute() api to send the data without
 response.

changes from v1(https://github.com/rdkcentral/Thunder/pull/691):- 

- _error set to Core::ERROR_NONE
- Used Exchange(time, cmd) instead of Send

### CODE REVIEW

**Review by sebaszm — APPROVED** [review]
Looks good.

**Comment by pwielders** [comment]
I will cherry pick this on the master. @vijs to merge this to R2.

**Comment by rjpdasilva** [comment]
@Preejar, @pwielders, @MFransen69, anything preventing this to be merged?

**Comment by rjpdasilva** [comment]
Hi @vijs, could you please provide your feedback regarding this PR?

**Comment by rjpdasilva** [comment]
@pwielders, @MFransen69, @vijs, can we please follow up on this PR?  
Either merge it, request some changes or tell us if we should just close it?

**Comment by karuna2git** [comment]
Hi @rjpdasilva ,
The change is good and we will get this merged today.

Thanks,
Karunakaran A

**Review by karuna2git — APPROVED** [review]

**Pull request merged**
