### PR TITLE
Thunder: moved bluetooth and broadband to ThunderLibraries

### PR DESCRIPTION
**Pull request by HaseenaSainul**

### CODE REVIEW

**Review by sebaszm — CHANGES_REQUESTED** [review]
I looks like you've pushed binaries and proxystub code? :)

**Comment by HaseenaSainul** [comment]
> I looks like you've pushed binaries and proxystub code? :)

Oh..sorry, will remove that :)

**Comment by HaseenaSainul** [comment]
> I looks like you've pushed binaries and proxystub code? :)

yes, it is removed :)

**Review by sebaszm — APPROVED** [review]
Looking good now!

**Pull request merged**
