### PR TITLE
BD-906:Relicense Thunder to Metrological Apache

### PR DESCRIPTION
**Pull request by mallikarjuna54**

### CODE REVIEW

**Comment by mhughesacn** [comment]
Thanks Mallikarjuna,
A few more RDK Headers I am seeing please:

    cmake/modules/FindSlauncher.cmake
    Source/processcontainers/implementations/AWCImplementation/AWCImplementation.h
    Source/processcontainers/implementations/AWCImplementation/AWCImplementation.cpp

I noticed these missing, please add Metrological headers:
	Source/com/ConnectorType.cpp
	Source/com/ConnectorType.h
	Source/plugins/Types.h
	Source/processcontainers/implementations/CRunImplementation/CRunImplementation.cpp
	Tests/cryptography/NetflixVaultGenerator/main.cpp
	Tests/loader/CMakeLists.txt
	Tests/loader/main.cpp
	Tests/unit/core/test_doorbell.cpp
	Tests/unit/core/test_statetrigger.cpp

Thanks

**Comment by mhughesacn** [comment]
Thanks Mallikarjuna - happy from compliance point of view

**Review by pwielders — DISMISSED** [review]

**Comment by pwielders** [comment]
@mallikarjuna54  Sorry, seems there is a merge conflict again. Could you remove the Test/cryptography from the list and I will immediatly merge it before anything else :-) Sorry!

**Comment by pwielders** [comment]
@mhughesacn Oops The Black Duck disagrees again :-)

**Comment by mhughesacn** [comment]
Hi Pierre.  We all have to jump together.  I upvote here and tweak the grumpy Duck so it likes Metrological headers and dislikes RDK ones.  So: please comment here saying when you are going to merge, and then I do these steps, and you merge and everything is happy.  Or just pick a time.
Thanks,
Martin

**Comment by pwielders** [comment]
@mhughesacn I am now blocking all other work to finally get these new headers in, to avoid new merge conflicts so if you approve them now I merge them immediately!

**Review by pwielders — APPROVED** [review]

**Pull request merged**
