### PR TITLE
fix find lxc cmake includes path

### PR DESCRIPTION
**Pull request by kiran-kottarathil-infosys**
fix find lxc cmake includes path

### CODE REVIEW

**Review by pwielders — DISMISSED** [review]

**Comment by pwielders** [comment]
@kiran-kottarathil-infosys can you update you pull request with the master so I can merge it? Seems I can not do it..

**Comment by abhayadev-sankaran-infosys** [comment]
@pwielders i rebased this branch, could you please check and merge if all ok?
CC @kiran-kottarathil-infosys

**Comment by pwielders** [comment]
@abhayadev-sankaran-infosys sorry will merge it as soon as you once more merge the master to this pull request!
So could you please the aster once more! Thanks!

**Comment by abhayadev-sankaran-infosys** [comment]
@pwielders its been rebased to latest master now, could you please check.
CC @kiran-kottarathil-infosys

**Review by pwielders — APPROVED** [review]

**Pull request merged**
