### PR TITLE
[PluginActivator] Improve logging & minor improvements

### PR DESCRIPTION
**Pull request by TeknoVenus**
Some minor improvements to the PluginActivator utility

* Use the stopwatch class to time activation for accuracy during NTP time sync
* Ability to set log level at runtime & add some debug messages (should probably switch logging to LocalTracer, but that's a job for another time...)
* Minor code tidy-up

### CODE REVIEW

**Review by pwielders — APPROVED** [review]
We are about to move this to a different location as it is being misused today so we would not want to "publish" to much but the changes look good!

**Comment by TeknoVenus** [comment]
Sounds good - let me know where you end up moving it to! :)

**Comment by pwielders** [comment]
@MFransen69 Where are we moving this ?

**Review by MFransen69 — APPROVED** [review]

**Comment by MFransen69** [comment]
> @MFransen69 Where are we moving this ?
@pwielders @TeknoVenus 

Wouter is taking care of that. Don't know if a new location was already discussed. Let me ask him when he is back from his holidays next week.

**Pull request merged**
