### PR TITLE
[WINDOWS] Windows is more picky about the sizes we use.

### PR DESCRIPTION
**Pull request by pwielders**
Create a warning free build in windows.

### CODE REVIEW

**Review by HaseenaSainul — APPROVED** [review]
LGTM

**Comment by pwielders** [comment]
@mhughesacn help.... what did we do wrong ?

**Comment by mhughesacn** [comment]
Hi @pwielders This file breaks my heart!  Changes to the file often trigger the tool because it can lose previous identifications.  That's what happened this time.  It doesn't help that it is very widely matching in the blackduck database.  Sorry for the inconvenience. - Martin

**Comment by pwielders** [comment]
@mhughesacn  Thanks!

**Pull request merged**
