### PR TITLE
[JsonGen] Fix interface to json RPC code generation

### PR DESCRIPTION
**Pull request by sebaszm**
Fixes some issues regarding JSON code generation from C++ interfaces, broken during addition of template support.

### CODE REVIEW

**Review by 404ag — CHANGES_REQUESTED** [review]
When JSONRPC is generated from the interface file, the generated event methods has wrong parameters types. i.e for
```c++
virtual void DialogueStateChange(const dialoguestate state) const = 0;
```
The generated method:
```c++
static void DialogueStateChange(PluginHost::JSONRPC& module, const DialogueStateChangeParamsData::StateType& state)
```
The expected method:
```c++
static void DialogueStateChange(PluginHost::JSONRPC& module, const dialoguestate & state)
```

**Comment by sebaszm** [comment]
> When JSONRPC is generated from the interface file, the generated event methods has wrong parameters types. i.e for
> 
> ```c++
> virtual void DialogueStateChange(const dialoguestate state) const = 0;
> ```
> 
> The generated method:
> 
> ```c++
> static void DialogueStateChange(PluginHost::JSONRPC& module, const DialogueStateChangeParamsData::StateType& state)
> ```
> 
> The expected method:
> 
> ```c++
> static void DialogueStateChange(PluginHost::JSONRPC& module, const dialoguestate & state)
> ```
Should be working now.

**Review by 404ag — CHANGES_REQUESTED** [review]
The generated code generated correct data type, however it lacks proper namespace name, as in the tested example the dialoguestate is inside of another class called INotification
Result:
```c++
static void DialogueStateChange(PluginHost::JSONRPC& module, const dialoguestate& state)
```
Expected:
```c++
static void DialogueStateChange(PluginHost::JSONRPC& module, const INotification::dialoguestate& state)
```

The parsed class:
```c++
struct IAVSController : virtual public Core::IUnknown {
    enum { ID = ID_AVSCONTROLLER };
    virtual ~IAVSController(){};
    struct INotification : virtual public Core::IUnknown {
            enum { ID = ID_AVSCONTROLLER_NOTIFICATION };
            virtual ~INotification(){};
            enum dialoguestate {
                IDLE,
                LISTENING,
                EXPECTING,
                THINKING,
                SPEAKING
            };
            virtual void DialogueStateChange(const dialoguestate state) const = 0;
        };
};
```

**Review by 404ag — APPROVED** [review]
After testing it LGTM

**Pull request merged**
