### PR TITLE
XIONE-1354: revert format C++ names

### PR DESCRIPTION
**Pull request by justin-ware-red**
Reason for change: commit 9eb937e changed the format of C++ names in JsonData_*.h header files. This is breaking existing code that uses these files.
Risks: Medium
Test Procedure: DRMActivationService plugin will build again.

Signed-off-by: Justin Ware <justin.ware@sky.uk>

### CODE REVIEW

**Comment by hteece** [comment]
Would also point out that while this is not a bundled service within RDK, the DTV service also suffers from this problem.

**Review by sebaszm — COMMENTED** [review]
This is breaking JSON-RPC glue generation from C++ headers.

**Comment by justin-ware-red** [comment]
Hi @sebaszm , are you saying that this change will "... break[ing] JSON-RPC glue generation from C++ headers." ? Was the change in the format of the C++ class names in the "JsonData_*.h" intentional and the new format will be the correct one going forwards? For example used to be "GetDrmIdentificationResultData" but is now "GetdrmidentificationResultData" for one of our JSON-RPC interfaces.

**Review by sebaszm — CHANGES_REQUESTED** [review]
Please change self.name to self.true_name. That should make both worlds work correctly.

**Comment by sebaszm** [comment]
Hi Justin, no, that was not intentional, but the change has impact on other code.

**Comment by justin-ware-red** [comment]
> Please change self.name to self.true_name. That should make both worlds work correctly.

Will do.

**Comment by justin-ware-red** [comment]
Hi @sebaszm , updated as you've suggested and can confirm this resolves our broken builds. I don't understand the wideer implications of this change though.

**Review by sebaszm — APPROVED** [review]
Good to merge!

**Comment by justin-ware-red** [comment]
Hi @sebaszm , thanks for the approval. I'm not authorized to do the merge will someone else be doing this?

**Comment by justin-ware-red** [comment]
On advice of Vjiay Selvaraj (ComCast) and Thunder component owner this pull request has been cancelled. The new behaviour of all lowercase generated C++ type names is now to be used.

**Comment by hteece** [comment]
I'm arguing this back, as we've currently got a mixed case here.

**Pull request merged**
