### PR TITLE
ONEM-21230 - fix payload size for control and jumbo frames

### PR DESCRIPTION
**Pull request by lukasz-wasylyk**
Two python script tests are attached, arguments are ipaddr and number of retries.
test_no_data shows error at closure, when close packet has payload (seems default in python). 
test_jumbo shows error and leads to assert when large data packet is being transmitted (>64kB)
[tests.zip](https://github.com/rdkcentral/Thunder/files/6858488/tests.zip)

### CODE REVIEW

**Review by mikolaj-staworzynski-red — APPROVED** [review]

**Review by pwielders — APPROVED** [review]

**Review by vijs — APPROVED** [review]

**Comment by pwielders** [comment]
@mhughesacn Could it be that the license/cla check crashed ? It is taking an awfull long time to complete..

**Comment by mhughesacn** [comment]
Hi @pwielders Request noted - checking with the team.

**Comment by pwielders** [comment]
@mhughesacn Thanks. Was it broken ?

**Comment by mhughesacn** [comment]
Hi @pwielders Not sure what went wrong - Steve disabled the check to unblock for now.  Still under investigation.

**Pull request merged**
