### PR TITLE
[compositorclient] Wayland: Weston update to xdg-shell stable protocol

### PR DESCRIPTION
**Pull request by petegriffin**
The following commits update the Weston compositor client code in Thunder to use xdg-stable protocol. This was merged in Weston 6 so we now have a dependency on Weston 6 or above.  Tested using Weston 8 on iMX8MQ-evk board.

### CODE REVIEW

**Comment by petegriffin** [comment]
@pwielders Please can you review this?
@kraj  @moorthy-bs fyi - updates to Thunder Weston wayland support

**Comment by mhughesacn** [comment]
Hi Pete,
Please will you make the following change: in NOTICE at top level, add the new block of copyrights for Kristian Høgsberg down to Red Hat.  You can put this after line 9 as a new separately licensed entity:

Copyright © 2008-2013 Kristian Høgsberg
Copyright © 2013 Rafael Antognolli
Copyright © 2013 Jasper St. Pierre
Copyright © 2010-2013 Intel Corporation
Copyright © 2015-2017 Samsung Electronics Co., Ltd
Copyright © 2015-2017 Red Hat Inc.
Licensed under the MIT license

When you have made these, I will still have to clear blackduck/copyright blocking i.e. it doesn't fix itself.  But I will keep an eye on it.
Thanks, Martin
Martin Hughes RDK CMF Compliance Team

**Comment by petegriffin** [comment]
@mhughesacn I just pushed an extra commit that updates NOTICE file like you requested

**Comment by mhughesacn** [comment]
Hi Pete.  Thanks for making the change.  I have done the approval work (hence all the rescanning), so these checks are clear now.  Martin

**Review by pwielders — APPROVED** [review]

**Pull request merged**
