### PR TITLE
REFPLTV-728: RDK Services: Controller.1.delete is not deleting the co…

### PR DESCRIPTION
**Pull request by swati-varahagiri**
…ntents of the directory

Reason for change: Files not getting deleted.
Test Procedure: Execute Controller.1.delete curl command.

### CODE REVIEW

**Review by pwielders — CHANGES_REQUESTED** [review]
Please use the cherry pick functionality of github to fix things that have already been fixed upstream. This avoids havoc in the administration of the github system as it than is aware that it is the same fix. And for this one, if you use the commit, the documentation generated for the JSONRPC interface is than updated accordingly :-)
https://github.com/rdkcentral/Thunder/commit/ab10cca278926aa87dab91eba85bd85c939be631
Use the hash above which is already available in R2.

**Comment by swati-varahagiri** [comment]
> Please use the cherry pick functionality of github to fix things that have already been fixed upstream. This avoids havoc in the administration of the github system as it than is aware that it is the same fix. And for this one, if you use the commit, the documentation generated for the JSONRPC interface is than updated accordingly :-)
> [ab10cca](https://github.com/rdkcentral/Thunder/commit/ab10cca278926aa87dab91eba85bd85c939be631)
> Use the hash above which is already available in R2.

Ok sure, thank you.

**Comment by pwielders** [comment]
@swati-varahagiri if it worked, can you or I close these pull request ?

**Comment by swati-varahagiri** [comment]
Will raise a new PR as per the suggestion.

**Pull request closed without merging**
