### PR TITLE
Add callsign support for Thunder plugins

### PR DESCRIPTION
**Pull request by goruklu**
Signed-off-by: Gurdal Oruklu <gurdal_oruklu@comcast.com>

### CODE REVIEW

**Review by pwielders — CHANGES_REQUESTED** [review]
I think this will break a lot of functionality. The Callsign (in case the config file is a separate entity) is equal to the name of this config file, without the json extension. You could, potentially, override this in the config by inserting this keyword. If you would now add this patch all plugins will get the same callsign, since typically we do not want to overwrite this callsign name (already depicted by the filename).
Why is this patch created, what was the usecase ?

**Comment by anand-ky** [comment]
Pierre - The use case is to be able to create fully qualified names for plugin callsigns like "org.rdk.DisplaySettings". We felt it would be easier to set this in the config file instead of changing the file name. If this parameter is not set in the config, it would use the name of the file as the callsign.

**Comment by pwielders** [comment]
> Pierre - The use case is to be able to create fully qualified names for plugin callsigns like "org.rdk.DisplaySettings". We felt it would be easier to set this in the config file instead of changing the file name. If this parameter is not set in the config, it would use the name of the file as the callsign.
Oke, that makes sense, and do agree to do it like that. Let me re-evaluate if we would than run into issues.

**Comment by pwielders** [comment]
Oke, that makes sense, and do agree to do it like that. Let me re-evaluate if we would than run into issues.

**Review by pwielders — APPROVED** [review]

**Comment by pwielders** [comment]
@sergiygladkyy can you please sign the CLA so I can merge this pull request ?

**Comment by sergiygladkyy** [comment]
Signed!

**Pull request merged**
