### PR TITLE
[JSON] Automatically escape UTF8 in JSON.

### PR DESCRIPTION
**Pull request by pwielders**
This pull request adds automatic transforming C++ style string to JSON compliant strings (using the /u escape sequence) during serialization and back on deserialization.

```
{
    // UTF8 for the violin music key: (byte array) f0 9d 84 9e => CodePoint 0x1D11E => UTF16 0xD834 0xDD1E
    string input = R"("Violin key sending: \uD834\uDD1E")";
    Core::JSON::String json;
    string received;

    json.FromString(input);
    json.ToString(received);
    EXPECT_STREQ(input.c_str(), received.c_str());
}
{
    string input = R"("Control: [25][\u0019] Character: [28][\u001C]")";
    Core::JSON::String json;
    string received;

    json.FromString(input);
    json.ToString(received);
    EXPECT_STREQ(input.c_str(), received.c_str());
}
```

### CODE REVIEW

**Review by MFransen69 — DISMISSED** [review]

**Review by ghost — COMMENTED** [review]
I have following input.json
{"getAvailableSSIDs":[{"ssid":"a\u03BB\u1F79\u03B3\u03BF\u03C5\u03C2b"}]}

It returns de-serialized ssid value as "a   b" instead of "aλόγουςb"
Is it a correct test?

**Comment by pwielders** [comment]
@neeraj-deshpande if understand correctly (see https://datatracker.ietf.org/doc/html/rfc7159#section-8.1) should the text be encoded UTF8 (as carried in the strings you set to the JSONstring). 
So I assume that
\u03BB = UTF16 => UTF8 (in string) => 0xce 0xbb
\u1F79 = UTF16 => UTF8 (in string) => 0xe1 0xbd 0xb9
\u03B3 = UTF16 => UTF8 (in string) => 0xce 0xb3
\u03BF = UTF16 => UTF8 (in string) => 0xce 0xbf
\u03C5 = UTF16 => UTF8 (in string) => 0xcf 0x85
\u03C2 = UTF16 => UTF8 (in string) => 0xcf 0x82

And indeed it should, if you show it as an UTF8 string show: "λόγους" but the string, should have the hex bytes as shown above.
I do think that there might be an issue in the code as it by default now pairs the codes (test case with the violin music key)  and it should only do that if it starts with the headers (D8XX/DCXX), so let me add this as a testcase and probably need o fix it....
So probably with the code now, you get that effect if you put a space between each code pair :-) so "a\u03BB \u1F79 
\u03B3 \u03BF \u03C5 \u03C2b" should result in "aλ ό γ ο υ ςb"

**Comment by ghost** [comment]
Yes. Above hex bytes are correct. If space is added, it is working fine.

**Comment by pwielders** [comment]
@neeraj-deshpande oke but than indeed you discovered a bug. Let me fix it before we merge this..

**Comment by pwielders** [comment]
Just added the testcase:
```
{
  //
  // \u03BB = UTF16 = > UTF8(in string) = > 0xce 0xbb
  // \u1F79 = UTF16 = > UTF8(in string) = > 0xe1 0xbd 0xb9
  // \u03B3 = UTF16 = > UTF8(in string) = > 0xce 0xb3
  // \u03BF = UTF16 = > UTF8(in string) = > 0xce 0xbf
  // \u03C5 = UTF16 = > UTF8(in string) = > 0xcf 0x85
  // \u03C2 = UTF16 = > UTF8(in string) = > 0xcf 0x82
  // It should show it as an UTF8 string show : "aλόγουςb" but the string, should have the hex bytes as shown above.
  string input = R"("a\u03BB\u1F79\u03B3\u03BF\u03C5\u03C2b")";
  Core::JSON::String json;
  string received;

  json.FromString(input);
  json.ToString(received);
  EXPECT_STREQ(input.c_str(), received.c_str());
}
```

**Comment by pwielders** [comment]
@neeraj-deshpande with this update I assume your test case should succeed now as wal (as expected)

**Review by ghost — DISMISSED** [review]
LGTM

**Review by HaseenaSainul — DISMISSED** [review]
LGTM

**Review by ghost — DISMISSED** [review]

**Review by HaseenaSainul — APPROVED** [review]
LGTM

**Review by ghost — APPROVED** [review]

**Review by MFransen69 — APPROVED** [review]

**Pull request merged**
